#!/bin/bash
set -e
worker/usage.sh "${BASH_SOURCE[0]}" '-noaes' -- "$@"

if [[ "$1" == '-noaes' ]]; then
  AES=1
  shift
else
  AES=0
fi

worker/welcome.sh

echo 'Will revoke the intermediate CA and create a new one.'
echo 'This will RESET the intermediate CA!'

worker/prompt.sh

echo 'Revoking old intermediate CA...'
plumbing/revoke.sh ca/root/ca.conf ca/intermediate/ca.crt superseded

# Both CRLs to be generated by intermediate.sh

declare -a ARGS=(-noaes)
if [[ $AES -eq 0 ]]; then
  ARGS=()
fi
worker/intermediate.sh "${ARGS[@]}"

worker/cacleanup.sh

echo
echo 'Intermediate CA has been Reset!'

exit 0
