#!/bin/bash
set -e
worker/usage.sh "${BASH_SOURCE[0]}" '-noaes' 'CA type' -- "$@"

if [[ "$1" == '-noaes' ]]; then
  AES=1
  shift
else
  AES=0
fi

echo 'Picking '"$1"' CA OCSP key...'
declare -a ARGS=(ca/"$1"/ocsp.key)
if [[ $AES -ne 0 ]]; then
  ARGS=(-noaes "${ARGS[@]}")
fi
plumbing/genkey.sh "${ARGS[@]}"

echo 'Making '"$1"' CA OCSP CSR...'
plumbing/request.sh ca/"$1"/init_req.conf ca/"$1"/ocsp.key ca/"$1"/ocsp.csr ocsp

echo 'Signing '"$1"' CA OCSP certificate...'
plumbing/casign.sh -y ca/"$1"/ca.conf ca/"$1"/ocsp.csr ca/"$1"/ocsp.crt ocsp

# CRL to be generated by caller

exit 0
